class LanguageConstants {
  static const Map<String, String> languageNames = {
    "en": "English",
    "la": "Latin",
    "tr": "Turkish",
    "fr": "French",
    "ja": "Japanese",
    "pi": "Pali",
    "th": "Thai",
    "id": "Indonesian",
    "hi": "Hindi",
    "pt": "Portuguese",
    "sr": "Serbian",
    "ar": "Arabic",
    "it": "Italian",
    "sa": "Sanskrit",
    "ml": "Malayalam",
    "hu": "Hungarian",
    "ru": "Russian",
    "xx": "No Language",
    "pl": "Polish",
    "ne": "Nepali",
    "da": "Danish",
    "el": "Greek",
    "ca": "catalan",
    "de": "German",
    "si": "Sinhalese",
    "es": "Spanish",
    "ko": "Korean",
  };
}
